### PR TITLE
feat: enable odos scroll

### PR DESCRIPTION
**Pull request by myz1237**
https://lifi.atlassian.net/browse/LF-8779

### CODE REVIEW

**Comment by myz1237** [comment]
why the test failed? Did I miss some setting?

**Comment by ezynda3** [comment]
@myz1237 can you get rid of the yarn.lock change in this PR?

**Comment by myz1237** [comment]
@ezynda3 thanks, ed. I did not notice that change

**Comment by ezynda3** [comment]
I'm going to approve this as it's not the main cause of the error. This started after merging another PR and we still need to debug it. DEX has been approved on Scroll.

**Comment by myz1237** [comment]
@ezynda3 It works now, thanks!

**Pull request merged**
