### PR TITLE
feat: whitelist 0x routers

### PR DESCRIPTION
**Pull request by myz1237**
# Which Jira task belongs to this PR?
https://lifi.atlassian.net/browse/LF-9741
# Why did I implement it this way?
- Add new AllowanceHolder Router to the whitelist lists
# Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] This pull request is as small as possible and only tackles one problem
- [ ] I have added tests that cover the functionality / test the bug
- [ ] I have updated any required documentation

# Checklist for reviewer (DO NOT DEPLOY and contracts BEFORE CHECKING THIS!!!)

- [x] I have checked that any arbitrary calls to external contracts are validated and or restricted
- [x] I have checked that any privileged calls (i.e. storage modifications) are validated and or restricted
- [x] I have ensured that any new contracts have had AT A MINIMUM 1 preliminary audit conducted on <date> by <company/auditor>

### CODE REVIEW

**Comment by myz1237** [comment]
One question: shall we delete previous approved router contracts after we successfully update 0x api from v1 to v2?

**Comment by maxklenk** [comment]
Please also add signature `0x2213bc0b`

**Review by maxklenk — APPROVED** [review]
The addresses and signatures are right.

**Comment by maxklenk** [comment]
The whitelisting has been synced to the chains supported by 0x.

**Comment by myz1237** [comment]
We need a sc core dev approve

**Review by 0xDEnYO — APPROVED** [review]

**Pull request merged**
